#!/bin/bash
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
CELADON="\033[38;5;86m"
HONEY="\033[38;2;204;169;50m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
echo -e "\e[32mloading...\e[0m"
clear
echo -e "\033[38;5;86m┌──────────────────────────────────────────┐\033[0m"
echo -e "                 FEATURE              $NC"
echo -e "\033[38;5;86m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[38;5;86m┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${CELADON}1.${NC} \033[38;2;204;169;50m RUNNING ${NC}"
echo -e "  ${CELADON}2.${NC} \033[38;2;204;169;50m SPEEDTEST ${NC}"
echo -e "  ${CELADON}3.${NC} \033[38;2;204;169;50m AUTOREBOOT ${NC}"
echo -e "  ${CELADON}4.${NC} \033[38;2;204;169;50m INFO PORT ${NC}"
echo -e "  ${CELADON}5.${NC} \033[38;2;204;169;50m CLEAR LOG {NC}"
echo -e "  ${CELADON}6.${NC} \033[38;2;204;169;50m BACKUP & RESTORE ${NC}"
echo -e "  ${CELADON}7.${NC} \033[38;2;204;169;50m REBOOT ${NC}"
echo -e "  ${CELADON}8.${NC} \033[38;2;204;169;50m RESTART ${NC}"
echo -e "  ${CELADON}9.${NC} \033[38;2;204;169;50m DOMAIN ${NC}"
echo -e "  ${CELADON}10.${NC} \033[38;2;204;169;50m CERT SSL ${NC}"
echo -e "  ${CELADON}11.${NC} \033[38;2;204;169;50m CLEAR CACHE ${NC}"
echo -e "\033[38;5;86m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 5 ] : " menu
case $menu in
1)
clear
run
;;
2)
clear
speedtest
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
3)
clear
autoreboot
;;
4)
clear
prot
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
5)
clear
clearlog
;;
6)
clear
menu-backup
;;
7)
clear
reboot
;;
8)
clear
restart
;;
9)
clear
addhost
;;
10)
clear
fixcert
;;
11)
clear
clearcache
;;
esac
